spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml